import type { RtlAnalysisFixture } from "@/lib/rtl/types";

const PR_184_ANALYSIS: RtlAnalysisFixture = {
  id: "rtl-pr-184-v1",
  prId: "pr-184",
  topModule: "spm",
  sourcePath: "src/spm.sv",
  status: "failed",
  simulator: "Icarus Verilog 12.0 · CI replay",
  synthesizer: "Yosys 0.46 · precomputed netlist",
  synthesizedAtRuntime: false,
  trace: [
    {
      cycle: 34,
      reset: 0,
      enable: 1,
      shiftedOperand: "16'h00A5",
      expectedAccumulator: "16'h00A5",
      actualAccumulator: "16'h00A5",
      status: "pass",
    },
    {
      cycle: 35,
      reset: 0,
      enable: 0,
      shiftedOperand: "16'h00A5",
      expectedAccumulator: "16'h00A5",
      actualAccumulator: "16'h014A",
      status: "fail",
    },
    {
      cycle: 36,
      reset: 0,
      enable: 0,
      shiftedOperand: "16'h0000",
      expectedAccumulator: "16'h00A5",
      actualAccumulator: "16'h014A",
      status: "fail",
    },
  ],
  log: [
    "[34] enable=1 accumulator=16'h00A5 PASS",
    "[35] enable=0 expected=16'h00A5 actual=16'h014A",
    "ASSERTION FAILED tb.spm_pipeline.accumulator_holds_when_disabled",
    "Simulation stopped after 1 failing assertion.",
  ],
  failure: {
    code: "RTL_ASSERT_FAIL",
    assertionId: "tb.spm_pipeline.accumulator_holds_when_disabled",
    cycle: 35,
    message: "Accumulator changed while enable was low.",
    failingNodeId: "accumulator_ff",
    expected: "16'h00A5",
    actual: "16'h014A",
    cause:
      "The new always_ff branch writes next_sum on every non-reset clock instead of preserving accumulator when enable is low.",
  },
  schematic: {
    width: 920,
    height: 360,
    nodes: [
      {
        id: "enable",
        kind: "input",
        label: "enable",
        detail: "1 bit",
        x: 32,
        y: 58,
        width: 112,
        height: 54,
      },
      {
        id: "shifted_operand",
        kind: "input",
        label: "shifted_operand",
        detail: "16 bit",
        x: 32,
        y: 238,
        width: 136,
        height: 54,
      },
      {
        id: "accumulator_q",
        kind: "register",
        label: "accumulator",
        detail: "Q · 16 bit",
        x: 218,
        y: 148,
        width: 132,
        height: 72,
      },
      {
        id: "next_sum_adder",
        kind: "operator",
        label: "+",
        detail: "next_sum",
        x: 420,
        y: 186,
        width: 88,
        height: 72,
      },
      {
        id: "enable_hold_mux",
        kind: "mux",
        label: "HOLD",
        detail: "enable path missing",
        x: 582,
        y: 112,
        width: 132,
        height: 72,
      },
      {
        id: "accumulator_ff",
        kind: "register",
        label: "accumulator",
        detail: "DFF · write always",
        x: 756,
        y: 176,
        width: 136,
        height: 76,
      },
      {
        id: "partial_sum",
        kind: "output",
        label: "partial_sum",
        detail: "16 bit",
        x: 756,
        y: 296,
        width: 136,
        height: 50,
      },
    ],
    edges: [
      { id: "edge-enable-hold", from: "enable", to: "enable_hold_mux", label: "unused" },
      {
        id: "edge-shifted-adder",
        from: "shifted_operand",
        to: "next_sum_adder",
        label: "shifted_operand",
      },
      {
        id: "edge-accumulator-adder",
        from: "accumulator_q",
        to: "next_sum_adder",
        label: "accumulator",
      },
      {
        id: "edge-adder-hold",
        from: "next_sum_adder",
        to: "enable_hold_mux",
        label: "next_sum",
      },
      {
        id: "edge-hold-ff",
        from: "enable_hold_mux",
        to: "accumulator_ff",
        label: "unconditional write",
      },
      {
        id: "edge-ff-output",
        from: "accumulator_ff",
        to: "partial_sum",
        label: "partial_sum",
      },
      {
        id: "edge-feedback",
        from: "accumulator_ff",
        to: "accumulator_q",
        label: "feedback",
      },
    ],
    highlightNodeIds: ["enable_hold_mux", "accumulator_ff"],
    highlightEdgeIds: ["edge-enable-hold", "edge-hold-ff"],
  },
};

export const RTL_ANALYSIS_FIXTURES: Record<string, RtlAnalysisFixture> = {
  [PR_184_ANALYSIS.id]: PR_184_ANALYSIS,
};
