"""Extract the curated SKY130 crop used by the demo.

Usage:
  python -m pip install gdstk==0.9.61
  python scripts/extract_tinytapeout_gds.py path/to/tinytapeout.gds

The source GDS is TinyTapeout/tinytapeout_gds_viewer's bundled
public/tinytapeout.gds at revision 2969b5e7b4004cc35875738ee53fa3043fd6b415.
"""

from __future__ import annotations

import json
import pathlib
import sys

import gdstk


ROOT = pathlib.Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "lib" / "layout" / "tinytapeout-data.ts"
CROP_UM = (20, 38, 50, 51)

LAYERS = {
    (64, 20): "nwell",
    (65, 20): "diffusion",
    (66, 20): "poly",
    (66, 44): "licon",
    (67, 20): "local-interconnect",
    (67, 44): "mcon",
    (68, 20): "metal1",
    (68, 44): "via1",
    (69, 20): "metal2",
    (69, 44): "via2",
    (70, 20): "metal3",
}


def extract(gds_path: pathlib.Path) -> list[tuple[str, list[list[int]]]]:
    library = gdstk.read_gds(gds_path)
    top_cells = library.top_level()
    if len(top_cells) != 1 or top_cells[0].name != "spm":
        raise RuntimeError("Expected the bundled TinyTapeout sample's single 'spm' top cell")

    top = top_cells[0]
    top.flatten()

    x1, y1, x2, y2 = CROP_UM
    crop = gdstk.rectangle((x1, y1), (x2, y2))
    result: list[tuple[str, list[list[int]]]] = []

    for (gds_layer, layer_name) in LAYERS.items():
        layer_polygons = [
            polygon
            for polygon in top.polygons
            if (polygon.layer, polygon.datatype) == gds_layer
        ]
        clipped = gdstk.boolean(
            layer_polygons,
            [crop],
            "and",
            precision=0.001,
            layer=gds_layer[0],
            datatype=gds_layer[1],
        )
        for polygon in clipped:
            points_nm = [
                [round((x - x1) * 1000), round((y - y1) * 1000)]
                for x, y in polygon.points
            ]
            result.append((layer_name, points_nm))

    return result


def write_typescript(polygons: list[tuple[str, list[list[int]]]]) -> None:
    lines = [
        'import type { LayerId } from "./types";',
        "",
        "// Generated by scripts/extract_tinytapeout_gds.py. Do not hand-edit.",
        "export const TINYTAPEOUT_POLYGONS: readonly [",
        "  LayerId,",
        "  readonly (readonly [number, number])[],",
        "][] = [",
    ]
    for layer, points in polygons:
        lines.append(f'  ["{layer}",{json.dumps(points, separators=(",", ":"))}],')
    lines.extend(["];", ""])
    OUTPUT.write_text("\n".join(lines))


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit("Pass the path to tinytapeout.gds")
    polygons = extract(pathlib.Path(sys.argv[1]))
    write_typescript(polygons)
    print(f"Wrote {len(polygons)} polygons to {OUTPUT}")
